version: "3.9"

services:
  zooweeper-0:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: zooweeper_server:latest
    ports:
      - "8080:8080"

  zooweeper-1:
    image: zooweeper_server:latest
    ports:
      - "8081:8080"

  zooweeper-2:
    image: zooweeper_server:latest
    ports:
      - "8082:8080"

  # kafka servers
  kafka-server-0:
    build:
      context: ./kafka-server
      dockerfile: Dockerfile
    image: kafka_server:latest
    ports:
      - "9090:9090"

  kafka-server-1:
    image: kafka_server:latest
    ports:
      - "9091:9090"

  kafka-server-2:
    image: kafka_server:latest
    ports:
      - "9092:9090"

  kafka-react-app:
    build:
      context: ./kafka-react-app
      dockerfile: Dockerfile
    image: kafka_react_app:latest
    ports:
      - "3000:3000"
