version: "3.9"

services:
  # zookeeper servers
  zookeeper:
    build: ./server
    ports:
      - "8080:8080"

  zookeeper-1:
    build: ./server
    ports:
      - "8081:8080"

  zookeeper-2:
    build: ./server
    ports:
      - "8082:8080"
  # kafka servers
  kafka:
    build: ./kafka-server
    ports:
      - "9092:9092"

  kafka-1:
    build: ./kafka-server
    ports:
      - "9093:9092"

  kafka-2:
    build: ./kafka-server
    ports:
      - "9094:9092"

  # web servers
  web:
    build: ./kafka-react-app
    ports:
      - "3000:3000"
