version: "3.9"

services:
  zooweeper-0:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: zooweeper_server:latest
    environment:
      - PORT=8080
      - BASE_URL=http://host.docker.internal
    ports:
      - "8080:8080"

  zooweeper-1:
    image: zooweeper_server:latest
    environment:
      - PORT=8081
      - BASE_URL=http://host.docker.internal
    ports:
      - "8081:8081"

  zooweeper-2:
    image: zooweeper_server:latest
    environment:
      - PORT=8082
      - BASE_URL=http://host.docker.internal
    ports:
      - "8082:8082"
  zooweeper-3:
    image: zooweeper_server:latest
    environment:
      - PORT=8083
      - BASE_URL=http://host.docker.internal
    ports:
      - "8083:8083"
  zooweeper-4:
    image: zooweeper_server:latest
    environment:
      - PORT=8084
      - BASE_URL=http://host.docker.internal
    ports:
      - "8084:8084"
  zooweeper-5:
    image: zooweeper_server:latest
    environment:
      - PORT=8085
      - BASE_URL=http://host.docker.internal
    ports:
      - "8085:8085"
  zooweeper-6:
    image: zooweeper_server:latest
    environment:
      - PORT=8086
      - BASE_URL=http://host.docker.internal
    ports:
      - "8086:8086"
  zooweeper-7:
    image: zooweeper_server:latest
    environment:
      - PORT=8087
      - BASE_URL=http://host.docker.internal
    ports:
      - "8087:8087"

  # kafka servers
  kafka-server-0:
    build:
      context: ./kafka-server
      dockerfile: Dockerfile
    image: kafka_server:latest
    environment:
      - PORT=9090
      - BASE_URL=http://host.docker.internal
    ports:
      - "9090:9090"

  kafka-server-1:
    image: kafka_server:latest
    environment:
      - PORT=9091
      - BASE_URL=http://host.docker.internal
    ports:
      - "9091:9091"

  kafka-server-2:
    image: kafka_server:latest
    environment:
      - PORT=9092
      - BASE_URL=http://host.docker.internal
    ports:
      - "9092:9092"

  kafka-react-app-0:
    build:
      context: ./kafka-react-app
      dockerfile: Dockerfile
    image: kafka_react_app:latest
    environment:
      - PORT=3000
      - BASE_URL=http://host.docker.internal
    ports:
      - "3000:3000"

  kafka-react-app-1:
    image: kafka_react_app:latest
    environment:
      - PORT=3001
      - BASE_URL=http://host.docker.internal
    ports:
      - "3001:3001"
